export const FETCH_POKEMON = 'FETCH_POKEMON';

export const TERM_POKEMON = 'TERM_POKEMON';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';

export const ORDER_POKEMON_BY_NAME = 'ORDER_POKEMON_BY_NAME';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FINISH_CART = 'FINISH_CART';
